name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@main
      with:
        host: 91.212.174.236
        port: 22
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /srv/testSSH
          git reset --hard HEAD^
          git pull
