name: CD

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          
          #Navigate to Project
          cd /srv/testSSH

          #Install npm forever
          npm list -g forever || npm install -g forever
          
          #Deploy Code
          git reset --hard HEAD^
          git pull
          
          #Restart App
          forever restart index.js || forever start index.js
